### ISSUE TITLE
best ig-platform-id

### ISSUE THREAD

**Issue by armenio** [RehabMan/OS-X-Clover-Laptop-Config#1]
The best choice for ig-platform-id on intel hd 5500 is 0x16260006

**Comment by RehabMan** [comment]
The best will depend on which one works.  Not enough data at this point to declare a winner.

**Comment by RehabMan** [comment]
I'll re-open as a reminder to revisit as time goes on and more data is provided by users that have the hardware.

**Comment by armenio** [comment]
ok! thanks.
For improve user data, look 2 success cases when it was changed the ig-platform-id 0x16160002 to 0x16260006:

 http://www.tonymacx86.com/yosemite-laptop-support/161591-intel-hd-graphics-5500-need-some-help-14.html#post1076812

and

http://www.tonymacx86.com/yosemite-laptop-support/164591-solved-wake-up-everything-returns-normal-audio-brughtness-less-display-9.html#post1045230

**Comment by RehabMan** [comment]
We'll try it for a while... 8ff3a5066cdff09d686fdd08207b4d4772cbea62

**Comment by casparzed** [comment]
Good
