### ISSUE TITLE
Found 5Ghz strange about AirPortBrcm4360 patch on Sierra

### ISSUE THREAD

**Issue by gongzhenjeef** [RehabMan/OS-X-Clover-Laptop-Config#10]
I have a BCM94352 replaced on my Laptop. When installing 10.12, I struggled with the Wi-Fi as even with your Fake-PCI-ID installed and patch on, it may still show that no hardware installed. And when everything are almost finished, both the kext and the patch seems to work.
However, I noticed recently that the Wi-Fi patch still have problems. When I reboot the system, it has access to 5Ghz network, and after about 10 seconds, it drop to 2.4G and the 5G channels doesn't show up in the System Report. 
![screen shot 2016-09-24 at 01 13 26](https://cloud.githubusercontent.com/assets/2020136/18795759/a9c1203a-81f8-11e6-8827-0ae01f0812df.png)
![screen shot 2016-09-24 at 01 29 14](https://cloud.githubusercontent.com/assets/2020136/18795802/dde86c38-81f8-11e6-83db-2cd9bdb48e4d.png)
![screen shot 2016-09-24 at 01 40 32](https://cloud.githubusercontent.com/assets/2020136/18795807/e1878874-81f8-11e6-9010-d873eafa8ee3.png)

As the hardware works well, I supposed that there may be something that could be enhanced with the AirPortBrcm4360 patch in Sierra.

**Comment by RehabMan** [comment]
This is not the place for support.  Use the forums on tonymacx86.com.
