### ISSUE TITLE
Sierra HD 5300 Cube I7 Stylus

### ISSUE THREAD

**Issue by kaiyes** [RehabMan/OS-X-Clover-Laptop-Config#13]
Hi @RehabMan . Is it possible to get full QE/CI for HD 5300 in Sierra ? I was able to achieve full QE/CI in el capitan with my cube i7 stylus which has core M processor with HD 5300.  But unfortunately I can't enable it in sierra. Any pointers on how to use this config plist ?

**Comment by RehabMan** [comment]
Procedures in Sierra are the same as for El Capitan.
This is not the place for support.  Use the forums.
