### ISSUE TITLE
Intel Core i7 7Y75

### ISSUE THREAD

**Issue by henningwerner** [RehabMan/OS-X-Clover-Laptop-Config#16]
Config available?

http://ark.intel.com/products/95441/Intel-Core-i7-7Y75-Processor-4M-Cache-up-to-3_60-GHz

**Comment by RehabMan** [comment]
Try config_HD620.plist

**Comment by henningwerner** [comment]
Okay, I would give it a try as soon as the device is in my hands.
So there should be no different in config between the HD615 and the HD620?

**Comment by RehabMan** [comment]
> So there should be no different in config between the HD615 and the HD620?

Not possible to predict the future. But probably not.

**Comment by RehabMan** [comment]
Closing due to lack of feedback.

**Comment by henningwerner** [comment]
Can you please reopen it.
I now have the device with Intel HD615 , I used provided plist.

Problem is I have no QE/CI (Graphics acceleration).

Do you need any data from me to fix this?

macOS: 10.12.4

**Comment by RehabMan** [comment]
Use the forums (tonymacx86.com laptop section) to debug your issue.
