### ISSUE TITLE
Increase 128MB DVMT-prealloc to 512MB or even 1024MB

### ISSUE THREAD

**Issue by TouchManage** [RehabMan/OS-X-Clover-Laptop-Config#17]
Hi, 

First of all : I love your work. It helped me so much in my hackintosh journey.

I would like to know if there is a way to go beyond 128MB DVMT prealloc. I have an Asus UX303 with 13" QHD display. It works great with 128MB DVMT, full QE/CI acceleration.

But i would like to know if it is possible to increase this number. In my bios I can set 512MB, and even 1024MB. Is there a way to enable 512 or 1024MB DVMT prealloc ?

Thanks in advance !

From a french hackintosher :)

**Comment by RehabMan** [comment]
You could set it in BIOS, then use Clover KextsToPatch to patch the framebuffer to match.

**Comment by TouchManage** [comment]
How can I determine the Hex value ? I tried to find how you did for 96MB and 128MB (pratically the same Hex value, but 96MB ending by 6 and 128MB by 8.) It's the same Azul kext to patch right ?

**Comment by RehabMan** [comment]
> How can I determine the Hex value ?
The replace value is the size.
For example, 128mb patch:
08002e0a 01030303 00000008
0x08000000 (byte reversed) is 128mb (128mb = 1024*1024*128)

>  It's the same Azul kext to patch right ?
No idea if your laptop is Haswell or not.  You didn't provide hardware details.

**Comment by TouchManage** [comment]
Sorry yes it's an Haswell, with HD4400. So I would need to convert 1024_1024_512 _**OR**_ 1024_1024_1024 to the reversed bytes. With an Hex converter or something ? (Like http://www.binaryhexconverter.com/)

**Comment by RehabMan** [comment]
You can use Calculator in OS X/macOS.
It has a programmer mode where you can do decimal/hex conversions,etc.

**Comment by TouchManage** [comment]
I'm a bit stuck.
Results : 
   512MB = 20000000
   1024MB = 40000000

So I suppose I need to transform those numbers to 0x20000000 **OR** 0x40000000
Then after that to 08002e0a 01030303 00000020 **OR** 00000040

I am correct ?

Thanks in advance

**Comment by RehabMan** [comment]
Yes.
