### ISSUE TITLE
Intel HD 4400 config.plist doesn't work !!!

### ISSUE THREAD

**Issue by EGYbkgo9449** [RehabMan/OS-X-Clover-Laptop-Config#18]
Hey,
I've used the config list for HD 4400 for Sierra 10.12 but it didn't even appear in the clover boot menu !

**Comment by RehabMan** [comment]
It is because you forgot HFSPlus.efi.
Read the guide.  Carefully.

**Comment by EGYbkgo9449** [comment]
Thanks that worked #lol
But it doesn't let me use my laptop keyboard, the mouse works cuz I've a wireless mouse but the laptop keyboard doesn't work, it asks for a Bluetooth keyboard and I don't have one, please help 😔

**Comment by EGYbkgo9449** [comment]
Nvm about that, I solved it :) ^^^
Thx bro :)

**Comment by MatchesMalonee** [comment]
@EGYbkgo9449 Please describe how you solved the issue.

**Comment by zanish888** [comment]
> Hey,
> I've used the config list for HD 4400 for Sierra 10.12 but it didn't even appear in the clover boot menu !
Sir can you send me the link from where i can download confit.plist file for intel hd4400 plz
