### ISSUE TITLE
the HD620's id should be 5916

### ISSUE THREAD

**Issue by cuikangyi** [RehabMan/OS-X-Clover-Laptop-Config#19]
my pc is dell ins 7460 with i5 7200u(hd620).
the id for hd620 shoud be 0x5916 in SSDT-IGPU.dsl, but bot 0x5919
this is from  my windows Device Manager:
> PCI\VEN_8086&DEV_5916&SUBSYS_07811028&REV_02

**Comment by RehabMan** [comment]
Thanks. Fixed typo.
