### ISSUE TITLE
Hang after loading screen

### ISSUE THREAD

**Issue by naveenSharma5415** [RehabMan/OS-X-Clover-Laptop-Config#2]
Hi, RehabMan. i import " config_HD3000_1366x768.plist " in clover it works great with yosemite 10.10.1. but after update to 10.10.4 my laptop stuck after loading bar. you can check here 

https://www.youtube.com/watch?v=osyFOuqQAAs

**Comment by RehabMan** [comment]
No idea without details/specs.  This is not a troubleshooting forum.
