### ISSUE TITLE
HD 5500 and Mac OS 10.12

### ISSUE THREAD

**Issue by theman480** [RehabMan/OS-X-Clover-Laptop-Config#20]
Hello RehabMan, first thank you for your amazing Work.
So I'm using your config with my Dell Inspirion 5558.
Here's:

```
 <dict>
            <key>Comment</key>
           <string>Disable minStolenSize less or equal fStolenMemorySize assertion, 10.12</string>
         <key>Enabled</key>
           <false/>
           <key>Name</key>
            <string>AppleIntelBDWGraphicsFramebuffer</string>
         <key>Find</key>
         <data>iUXIOcd2Tw==</data>
        <key>Replace</key>
          <data>iUXIOcfrTw==</data>
     </dict>
```

I tried first change the ig-platform-id  to the invalid one (0x12345678) when i try to boot i have the kernel panic with the forbidden icon.

Then i tried with 0x16260006 the ig-platform-id that match with my hd 5500 same kernel panic with the forbidden icon.

Can you help me? I think i did everything right.

Thank you in advance.

**Comment by RehabMan** [comment]
Use the forums.  This is not the appropriate place for troubleshooting your mistake.
