### ISSUE TITLE
Propose to add minStolenSize patch for 10.13

### ISSUE THREAD

**Issue by PMheart** [RehabMan/OS-X-Clover-Laptop-Config#24]
Hello RehabMan,
I'm proposing to add these patches for BDW, SKL, KBL and the patches can be checked out at [HERE](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1696023&page=9&extra=#pid47234915).
Sorry that the post above is in Chinese, and I wish you could forgive that, the major stuffs you need is in the spoiler. :)

Best regards,
PMheart

**Comment by RehabMan** [comment]
I will probably remove the minStolenSize patch entirely, or add it to config_patches.plist (for archiving).
The minStolenSize patch was always a bad idea... it is better to patch the framebuffer data for actual DVMT-prealloc setting.

**Comment by PMheart** [comment]
Ah, I've nearly completely forgotten this old issue...
IMHO patching text segment could be more universal, however, patching FB data is only for particular ig-platform-id.
Ok, issue closed.

**Comment by RehabMan** [comment]
Keeping this issue open so I remember to remove the minStolenSize patches or move them to config_patches.plist (or maybe a separate config_archive.plist).

**Comment by RehabMan** [comment]
Moved minStolenSize patches to config_deprecated.plist.
