### ISSUE TITLE
1920x1080 HD3000 Mobile

### ISSUE THREAD

**Issue by Invictaz** [RehabMan/OS-X-Clover-Laptop-Config#25]
The config.plist are now upto 1600x900 but no config.plist is there yet for 1920x1080 (HD3000 mobile) with Duallink. Can you please upload one with Nvidia card disabled and the other fixes?

**Comment by RehabMan** [comment]
1600x900 applies to 1920x1080 as well.
Key is duallink.
900p and 1080p are both dual link.
