### ISSUE TITLE
config_HD4600_4400_4200.plist - Grey screen and noise

### ISSUE THREAD

**Issue by Calcyfer** [RehabMan/OS-X-Clover-Laptop-Config#28]
I have a HP 450 G2 with intel HD 4400 graphics. When I use the `config_HD4600_4400_4200.plist` plist, I get a grey screen with coloured noise and lines at the bottom (where the login screen should be), the UI itself isn't visible.

Using `config_HD4000_1600x900.plist` the UI is fine (with expected flashing on grey gradients), but I don't seen to get hardware acceleration.

Any ideas? OS is Sierra.

Thanks!

**Comment by RehabMan** [comment]
Use the forums.
This is not the place to troubleshoot your mistake.

**Comment by Calcyfer** [comment]
Wow. Thanks for that _overly-friendly_ reply.
[sarcasm off] Thanks for your work on everything though. :)

**Comment by RehabMan** [comment]
Just the facts, mate.
