### ISSUE TITLE
Few suggestion and fixup with SSDT-IGPU.

### ISSUE THREAD

**Issue by gujiangjiang** [RehabMan/OS-X-Clover-Laptop-Config#33]
1、We can add intel 8 process support such as UHD620(Fake as HD520 not HD620.)

> 
            // Coffee Lake/UHD620
            0x5917, 0, Package()
            {
                "AAPL,ig-platform-id", Buffer() { 0x00, 0x00, 0x16, 0x19 },
                "model", Buffer() { "Intel UHD Graphics 620" },
                "device-id", Buffer() { 0x16, 0x19, 0x00, 0x00 },
                "hda-gfx", Buffer() { "onboard-1" },
                "RM,device-id", Buffer() { 0x16, 0x19, 0x00, 0x00 },
                "AAPL,GfxYTile", Buffer() { 1, 0, 0, 0 },
            },
> 

2、The HD5300 with Intel Core M have wrong ig-platform-id and can cause some problems.

Right ID is 0x16260006 and with no problem and Clover suggest 16260006 by default.

If i use 16260004 i cause cant wake up laptop and only see blackscreen but if i use 16260006 it have no problem.

PS:My CPU is Intel Core M 5Y10c with HD5300 and using MacBook8,1.

**Comment by RehabMan** [comment]
1 is a dup of pr #31 
2 i can change, but also maybe should be 0x161e0000

**Comment by gujiangjiang** [comment]
@RehabMan 

Thanks for replay.

1.With Add UHD620 to SSDT-IGPU we need FakePCIID and FakeIntelHDGraphic to drive them and dont need modify these kexts.

2.0x161e0000 with no problem about blackscreen but it has wrong vram with 1024 not 1536.
- 0x161e0000 work well but vram shows 1024M.
- 0x16260004 work but when screen black it cant light anymore until restart macOS.
- 0x16260006 work well with no problem.It has right 1536M vram and dont have any blackscreen problem.

So i suggest HD5300 to use 0x16260006.

PS:I have seen the real MacBook(2015) with CoreM HD5300 have 1536 vram.So the 161e0000 was not the best choice for CoreM laptop.

Thanks in advance and forgive my poor english.

**Comment by RehabMan** [comment]
VRAM 1024 vs. 1536 is not necessarily wrong. Just different.  VRAM in Intel is variable, controlled by software, as there is no real VRAM in the device itself.  It always uses system RAM.

Your black screen issues might be caused by incorrect backlight configuration.
0x19260004 uses PWMMax 0x1499
0x19260006 uses PWMMax 0xad9
0x191e0000 uses PWMMax 0x1499

Whatever the ig-platform-id uses, when using SSDT-PNLF.aml, you must insure the LMAX matches the PWMMax of the ig-platform-id.

Furthermore, I consider SSDT-IGPU.aml "sample code" (for hotpatch guide).  It is expected you might make changes to meet your own needs.  Plus, as I wrote before, I provided an easy way to override with RMCF.IGPI.

**Comment by RehabMan** [comment]
SSDT-IGPU now updated for native KabyLake support and KabyLake-R HD620.
SSDT-SkylakeSpoof.aml can be included if you want Skylake spoof for KabyLake.
Ended up using 0x161e0000 for 8086:0x161e Broadwell.
People can change or override to their liking (by changing SSDT-IGPU.dsl or using RMCF.IGPI)

**Comment by gfoury** [comment]
Just out of curiosity--do you hear if `0x161e0000` works for people on Broadwell when others don't? I ended up on `0x16260006` for an i5-5200U, as well as on the Broadwell-generation Core m3 in the ASUS UX303. The Core m3 was *really* unhappy with `0x16260000`. But that's what guides are for, I guess.

**Comment by RehabMan** [comment]
Most of the content in SSDT-IGPU.dsl is guessing.
I don't have all the hardware to test with.
And different computers will need different settings.
I imagine that most are using Clover config.plist/Graphics/ig-platform-id to inject AAPL,ig-platform-id, and that is what I would recommend.
I use derived SSDT-IGPU code for guides that handle multiple different laptop models.    I go into it expecting that changes will need to be made that are specific to the hardware in question.

**Comment by gfoury** [comment]
I understand, and agree. Thank you.

**Comment by gujiangjiang** [comment]
@RehabMan 

New finding.

I find the real MacBook 8,1 With Core M HD5300 use **0x161e0001** not **0x161e0000**,And i test with 0x161e0001 and works well with no vram and blackscreen problem.

So i hope to fix this ig-platform-id.

Very thanks to you and best wishes.

**Comment by RehabMan** [comment]
Changed to 0x161e0001

**Comment by gujiangjiang** [comment]
@RehabMan 
I have delete the comment because i find 0x161e0001 cant boot into macOS.
So i want to know which is the real MacBook 8,1 ID？ 0001？0000？

I will test more time tonight.

**Comment by gujiangjiang** [comment]
Comfirmed that 161e0001 cant work with HD5300...

Sorry for my mistake.

I will talk to @BarbaraPalvin to comfirm what is the true id of HD5300 for Core M.

**Comment by RehabMan** [comment]
These ig-platform-id values are machine dependent.
There is no "one right answer".

**Comment by gujiangjiang** [comment]
@RehabMan 
OK thanks.

But the HD5300 maybe 161e0000 much better.
http://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?p=2546738
http://www.insanelymac.com/forum/topic/284656-clover-general-discussion/?p=2546776

Sherlock said he tested  dell venu pro 12 with HD5300 and have same result like me with only 0x161e0000 and 0x16260006 works.

So i think 0x161e0001 is not suitable for hackintosh just now and 0x161e0000 with be a better choose rather than 0x161e0001 nor 0x16260006.

Thanks rehabman for your work with hotpatch.
