### ISSUE TITLE
Please Config HD515

### ISSUE THREAD

**Issue by andrescas18** [RehabMan/OS-X-Clover-Laptop-Config#35]
Hi, 

Intel HD515 not work High Sierra, please create config file

**Comment by RehabMan** [comment]
Use config_HD520_530_540.plist.

**Comment by pjp401** [comment]
I used config_HD520_530_540.plist a while ago with a specific EFI file and it worked for high sierra, but I had to erase my hard drive and install high sierra again and when I use the config_HD520_530_540.plist the computer restarts at boot.
I have a Intel core m3-6y30 and Intel HD Graphics 515 (4gb).
Thank you in advanced.

**Comment by andrescas18** [comment]
What version from high Sierra? 10.13 or 10.13.1?. you use intelgraphicsfixup ? I have  a Intel Graphics 515 with 128 mb. You can send me your clover folder. Please help me!. I have the PAVP freezing and problem from logo.

**Comment by pjp401** [comment]
I'm on 10.13.2, I have Intel graphics fixup.

**Comment by pjp401** [comment]
The default config is a different one, the config in the efi file that is named config-1 is the config_HD520_530_540.plist 
[EFI.zip](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/files/1588045/EFI.zip)

**Comment by RehabMan** [comment]
Guide:
https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/

**Comment by andrescas18** [comment]
pjp401 please upload your personal efi clover folder and config on install and installed. this efi folder https://github.com/RehabMan/OS-X-Clover-Laptop-Config/files/1588045/EFI.zip

not work and not include kexts

**Comment by RehabMan** [comment]
rename config_HD520_530_540.plist => config_HD515_520_530_540.plist
resolves this issue.
