### ISSUE TITLE
Cant make my hackintosh stable

### ISSUE THREAD

**Issue by ulfuls14** [RehabMan/OS-X-Clover-Laptop-Config#39]
Hello Everyone,

I have been working on my hackintosh for about 5 days now installing high sierra 10.13.2. This has been one of the most challenging builds I have done in my life. Im stuck and have no idea what to do. I cant get it to run stable. Either I have no audio, no internet, or no graphics card. When all 3 work the preboot corrupts the install. I have tried many avenues of fixing this from updated kext files, updating clover, multibeast, clover configurator, reinstalls, formats, its just baffling me. can anyone help me to fix my hackintosh?

Fixes I need

1. HDMI port on my 1050 ti never has worked after install completes. (only dvi works) 

- If I plug dvi to HDMI cable the screen goes blank. Unplugging a monitor while its on and plugging in another cause the build to glitch. 

2. Audio sometimes works. after a few reboots or messing with any setting i lose it.

- i have replaced and updated the lilu.kext, HDMIaudio.kext, AppleALC.kext, and tried to runn the .command 3.0 file i found on a site of rehabmans which crashes the clover bootloader. Multibeast will cause verbose to get suck in a log. I have tried all of these options with SIP enabled and disabled.

3. Sometimes messing with those 2 causes me to lose my internet.

- This is completely random. If I try to repair it I lose my NvidiaWebDrivers and get glitches on the screen

4. My Nvidia web drivers sometimes crash even though its updated.

- I have applied the FixNvidaGraphics.kext and tried to inject and remove inject.

5. Teach me how to clone this once we fix it and i can make a package download for all supplies needed to do this and upload it here for others. 

Thanks in advance!!!!

**Comment by RehabMan** [comment]
What kind of laptop is it?

**Comment by ulfuls14** [comment]
Its a desktop.  Asus H170 Pro with i7 6700K skylake and geforce 1050 ti

**Comment by RehabMan** [comment]
This repo is for laptops.
You should use the forums.
