### ISSUE TITLE
Not able to boot up installer for High Sierra even after using config_530

### ISSUE THREAD

**Issue by Detr0x** [RehabMan/OS-X-Clover-Laptop-Config#41]
Hi
I’m using an alienware laptop with Hd 530 as an integrated graphic and 1070gtx as dedicated.
Even after using the config_530 file i’m not able to boot into the installer for High Sierra.
![79614ed3-9031-4566-bfa5-b29d8f777b2e](https://user-images.githubusercontent.com/34805859/35822537-a0d88f44-0ad2-11e8-92a3-0794264a700f.jpeg)

I have attached a screen shot where in it can seen that i am stuck at IOUsersconsole screen.

Thank you

**Comment by RehabMan** [comment]
Use the forums.
The issues database here is for bug reports with complete information, not troubleshooting user mistakes.

**Comment by jayghimire** [comment]
How to download or save clover config.plist

**Comment by jayghimire** [comment]
?????

**Comment by RehabMan** [comment]
Please use the forums for help with such questions, NOT the issues database on github.
