### ISSUE TITLE
Laptop will not boot after config replacement

### ISSUE THREAD

**Issue by DatOneLefty** [RehabMan/OS-X-Clover-Laptop-Config#47]
On my Razer Blade Stealth, my iGPU only shows 21 MB of VRAM and everything is too small due to scaling, so I thought this could fix some issues. After installing and attempting to boot, when it gets to the end of the loading screen, its hows a few red apple logos in a line and a green loading bar, and then the screen goes blank. Am I doing anything incorrectly? I have the 2 kexts for FakePCIID installed

**Comment by nopdotcom** [comment]
You'll have better luck if you take this to the forums. Be sure to include the problem-reporting information.

**Comment by RehabMan** [comment]
Use the forums.  This is not the appropriate place to troubleshoot your mistake.
