### ISSUE TITLE
Wrong credits

### ISSUE THREAD

**Issue by vandroiy2013** [RehabMan/OS-X-Clover-Laptop-Config#51]
https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/e6f24ce5151fccc3e59a7c716818ac9c66c32f71/config_HD4600_4400_4200.plist#L460

Hi. This two kernel patches are not mine. Credits should go to @vit9696. 
Thanks!

**Comment by RehabMan** [comment]
Fixed. 

The reason you are credited... is because VirtualSMC FAQ, https://github.com/acidanthera/VirtualSMC/blob/master/Docs/FAQ.md, links to here: https://applelife.ru/threads/ustanovka-macos-high-sierra-10-13-na-intel-pc.2210706/page-358#post-686953
