### ISSUE TITLE
Desktop UHD630 without HDMI or DP signal after drive graphic card

### ISSUE THREAD

**Issue by ourfor** [RehabMan/OS-X-Clover-Laptop-Config#53]
> excuse me

I install mojove 10.14.1 in my desktop computer, here is my desktop information:
- cpu: i7 8700K
- gpu: uhd 630
- motherboard: asus z390-p
no extra gpu.

Any solution?

**Comment by RehabMan** [comment]
What is your point?

**Comment by eamigo86** [comment]
Hi @RehabMan, thanks in advance for you help and your advice in foros. I have successfully install Mojave in a Dell XPS 9570 (i7-8750H, 16GB RAM and 4K touch screen), but i can't get the HDMI output work, I tried with the onboard port and with a usb-c hub in thunderbolt port). 
I has managed to make work as the touchscreen feature, but this I have not been able to solve it, could you give me some advice?
