### ISSUE TITLE
No brightness slider?

### ISSUE THREAD

**Issue by twikoffin** [RehabMan/OS-X-Clover-Laptop-Config#54]
Hello. I have my own config before and brightness worked well, but after changing config to RehabMan I can't change brightness? Before I can do this without any kexts.
So, how to fix this trouble without any kexts?
![image](https://user-images.githubusercontent.com/32393163/48304967-f0274b80-e533-11e8-9817-2f603c412fb1.png)
P.S. now my display in displaying like PC monitor.

**Comment by RehabMan** [comment]
This is not the place to troubleshoot your mistake.
Please refer to the guide:
https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightfixup-kext.218222/
