### ISSUE TITLE
inquiry: setting for 128M DVMT

### ISSUE THREAD

**Issue by htpcrig** [RehabMan/OS-X-Clover-Laptop-Config#55]
Hi Rehabman
lenovo with HD5500 & Nvidia 920M.
i can disable nvidia in bios, but no option to adjust dvmt.

Windows report that it is set to 128MB.
does your current config for HD5500 support my 128MB setting or i need to lower it down via properties in config?

I read that 128MB will have issue on some laptop, and i think im having that problem.

I followed all your instruction especialy the fake ig-platform-id,  fix cache, then boot with 0x016260006

the KP im getting is usually about AppleIntelBDWGraphicsFramebuffer.

Note: 
Name: AppleIntelBDWGraphicsFramebuffer
Find: 06002616 01030303 00002002 00005001
Replace: 06002616 01030303 00003001 00009000
in kextopath works.

But not in devices>properties with whatevergreen

thanks :)

**Comment by Xc2333** [comment]
Hi! As Rehabman said;

**Windows is NOT a valid way to determine what DVMT-prealloc is set to. There is no correlation, especially with Windows 10.**

It's better to use WhateverGreen.kext to avoid DMVT KP,see here:https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Intel.md

**Comment by htpcrig** [comment]
hi Xc2333
I have read that too.thanks for reminding me :)

So my question is, should i  need change the existing value in config_hd5500 to try lower or higher the default? 
im not so sure on how it will be done though.

**Comment by RehabMan** [comment]
Existing github plists have patches for 32mb DVMT-prealloc as that is the most common setting.
