### ISSUE TITLE
Some help to solution to the HDMI output issue?

### ISSUE THREAD

**Issue by eamigo86** [RehabMan/OS-X-Clover-Laptop-Config#56]
Hi @RehabMan, thanks in advance for you help and your advice in forums.
I have successfully install Mojave in a laptop Dell XPS 9570 (i7-8750H, 16GB RAM and 4K touchscreen version), but I can not make the HDMI output work, I tried with the onboard port and with a usb-c hub in thunderbolt port.

These are the advances that I have achieved at the moment:
1. ~~Audio, no sound through internal speakers, although headphone jack are working.~~
2. Sometimes, Sleep action turn off the screen into a black screen and not wake up, and I have to restart by power button.
3. ~~It do not save the screen brightness level setting, when starting it is always at 75% or 80%.~~
4. ~~The advanced gestures of the trackpad do not work except the scroll with two fingers.~~(Fixed except "Smart Zoom" and "Notification Center" gestures).
5. Fingerprint sensor, wifi killer card and card reader not work (I have wifi by TP-Link TL-WN823N usb adapter).
6. ~~I can't find any option to change the behavior of function keys, to use default F keys without Fn key.~~
7. ~~Touchscreen does not work, I have not found anyone commenting on how to put this feature to work.~~ (Fixed, but I can not perform actions other than: select an icon, click or select a icons group)
8. HDMI port for audio and video output.
9. USB-C (Thunderbolt port) not working, for HDMI output.

Could you help me to fix it? Thanks in advance

**Comment by eamigo86** [comment]
Hi @loverto, thanks for advice but the AppleHDA knext it's for audio, and I have not problem with that. Thanks

**Comment by RehabMan** [comment]
Off-topic here.  Closing.
