### ISSUE TITLE
HDMI Audio not working on UHD620

### ISSUE THREAD

**Issue by h-okon** [RehabMan/OS-X-Clover-Laptop-Config#58]
as described, no HDMI AUDIO on UHD620.
HDMI Video works flawlessly.

**Comment by effeci** [comment]
Same problem here on kabylake 7700hq hd630

**Comment by loverto** [comment]
applealc

**Comment by h-okon** [comment]
AppleALC is installed and working flawlessly. Audio via jack / built-in speakers works without any problems.

**Comment by RehabMan** [comment]
Not related to this repo.  Closing.
