### ISSUE TITLE
add UHD resolution patches in config_HD520_530_540.plist ?

### ISSUE THREAD

**Issue by 0x2c0d** [RehabMan/OS-X-Clover-Laptop-Config#6]
hi,
 I just get a laptop xps 9550 with 4K resolution.
the bois is base on AMI but customize by dell, so there no option to change DVMT-prealloc in bios settings.
can you add support patches in config.plist ?

cpu   i7 6700HQ
motherboard chip  hm170
4k resolution
graphics card  intel hd930  and nvidia 960M

thank you.

**Comment by RehabMan** [comment]
There is already the minStolenSize patch.  But it is better to set DVMT-prealloc instead of using the patch.
