### ISSUE TITLE
Which plist should UHD 620 use?

### ISSUE THREAD

**Issue by undefinedplayer** [RehabMan/OS-X-Clover-Laptop-Config#64]
I have an i5-8250U CPU which comes with UHD 620 Graphic, I see there are two plist files may be suitable:
`config_HD615_620_630_640_650.plist`
`config_UHD630.plist`
Which one should I use?

**Comment by maier519** [comment]
i suggest choosing the 1th

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shawn Lin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午10:29
收件人:&nbsp;"RehabMan/OS-X-Clover-Laptop-Config"<OS-X-Clover-Laptop-Config@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[RehabMan/OS-X-Clover-Laptop-Config] Which plist should UHD 620 use? (#64)





 
I have an i5-8250U CPU which comes with UHD 620 Graphic, I see there are two plist files may be suitable:
 config_HD615_620_630_640_650.plist
 config_UHD630.plist
 Which one should I use?
