### ISSUE TITLE
How to drive Iris 6100 Graphics

### ISSUE THREAD

**Issue by LanFly** [RehabMan/OS-X-Clover-Laptop-Config#7]
I'm sorry to trouble you, but I really need your help.
I have a **mini host**, the configuration is as follows:
**I5 5157u CPU ES version**
**Integrated graphics iris 6100**
**AMI BIOS**
**Display interface HDMI**
My graphics card has been unable to drive.Show only 7M memory.Using the clover+GPT. OSX system is the 10.11.4 version. I try to inject 0x162b0000 ig-platform-id in clover, restart the machine can not open.
What can I do to drive the graphics card?
My email address is **bluescode@outlook.com**

**Comment by RehabMan** [comment]
Use the forums.  github issues are not for troubleshooting.
