### ISSUE TITLE
minStolen patch for 10.12

### ISSUE THREAD

**Issue by l2dy** [RehabMan/OS-X-Clover-Laptop-Config#9]
<dict>
				<key>Comment</key>
				<string>Disable minStolenSize less or equal fStolenMemorySize assertion, 10.12</string>
				<key>Disabled</key>
				<false/>
				<key>Name</key>
				<string>AppleIntelBDWGraphicsFramebuffer</string>
				<key>Find</key>
				<data>iUXIOcd2Tw==</data>
				<key>Replace</key>
				<data>iUXIOcfrTw==</data>
			</dict>

**Comment by RehabMan** [comment]
Your work or someone elses?

**Comment by l2dy** [comment]
Someone else's, verified on my laptop.

**Comment by RehabMan** [comment]
Please provide a link to the original author/source.  Otherwise, I have to ignore it and come up with the patch myself (it is not difficult).

Closing this for now.  You can re-open if you find the source/credit info.

**Comment by gfoury** [comment]
I am only a bystander, and I am sorry for the noise on a closed issue. But thank you for the effort and more importantly the honesty in this matter.
